"""Fetch per-block average colors from PrismarineJS/minecraft-assets textures.

The bundled ``schematica/data/block_colors.json`` ships a reference color table
generated by this module so previews look right out of the box. To generate a
color table for a specific Minecraft version (uses the closest available
minecraft-assets snapshot <= that version)::

    python -m schematica.blocks.colors 1.20.1
    python -m schematica.blocks.colors --assets 1.21.4
    python -m schematica.blocks.colors --list

The result is cached next to ``blocks.json`` as
``<cache_root>/data/pc/<version>/block_colors.json``; the preview renderer
picks it up automatically (newest cached version wins unless
``SCHEMATICA_BLOCK_COLORS`` overrides the path).

Only vanilla-style single-texture blocks get textured averages; biomes-tinted
blocks (grass/leaves) are multiplied by the plains-biome colormap tint so they
don't render gray. Everything is stdlib + numpy -- Pillow is *not* required:
a minimal PNG decoder handles the 16x16 RGB(A) textures the assets repo ships.
"""
from __future__ import annotations

import argparse
import base64
import json
import re
import struct
import sys
import zlib
from pathlib import Path
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

import numpy as np

from .download import _default_cache_root

_OWNER = "PrismarineJS"
_ASSETS_REPO = "minecraft-assets"
_RAW = f"https://raw.githubusercontent.com/{_OWNER}/{_ASSETS_REPO}/master/"
_API = "https://api.github.com"
_USER_AGENT = "schematica-colors/1.0"

# Blocks whose texture is grayscale and biome-tinted at render time.
_TINTED_GRASS = {"grass_block", "short_grass", "tall_grass", "fern", "large_fern",
                 "sugar_cane", "grass"}
_TINTED_FOLIAGE_RE = re.compile(r".*_leaves$", re.IGNORECASE)
_FOLIAGE_FIXED = {  # these leaves have their own color; only these get tinted
    "oak_leaves", "jungle_leaves", "acacia_leaves", "dark_oak_leaves",
    "mangrove_leaves", "spruce_leaves", "birch_leaves", "azalea_leaves",
    "flowering_azalea_leaves", "vine",
}


def _http_get(url: str, timeout: float = 60.0) -> bytes:
    req = Request(url, headers={"User-Agent": _USER_AGENT})
    try:
        with urlopen(req, timeout=timeout) as resp:
            return bytes(resp.read())
    except HTTPError as e:
        raise RuntimeError(f"HTTP {e.code} fetching {url}: {e.reason}") from e
    except URLError as e:
        raise RuntimeError(f"network error fetching {url}: {e.reason}") from e


def list_assets_versions(timeout: float = 30.0) -> list[str]:
    """List version directories available in PrismarineJS/minecraft-assets."""
    req = Request(f"{_API}/repos/{_OWNER}/{_ASSETS_REPO}/contents/data",
                  headers={"User-Agent": _USER_AGENT})
    with urlopen(req, timeout=timeout) as resp:
        entries = json.loads(resp.read())
    out = [e["name"] for e in entries if e.get("type") == "dir"
           and re.match(r"^\d+(\.\d+)+$", e["name"])]
    return sorted(out, key=_vkey)


def _vkey(v: str) -> tuple[int, ...]:
    return tuple(int(x) for x in v.split(".") if x.isdigit())


def best_assets_version(mc_version: str, *, timeout: float = 30.0) -> str:
    """Pick the newest minecraft-assets snapshot that is <= ``mc_version``.

    Falls back to the newest snapshot overall when none is older.
    """
    versions = list_assets_versions(timeout=timeout)
    if not versions:
        raise RuntimeError("could not list minecraft-assets versions")
    if mc_version in versions:
        return mc_version
    target = _vkey(mc_version)
    older = [v for v in versions if _vkey(v) <= (target[0], target[1])]
    return older[-1] if older else versions[0]


# --------------------------------------------------------------------------
# Minimal PNG decoder (stdlib zlib + numpy). Handles bit depths 1/2/4/8 for
# greyscale (type 0) and palette (type 3) images and depth 8 for RGB (2) and
# RGBA (6), which covers the whole vanilla texture set.
# --------------------------------------------------------------------------

def _unfilter(raw: bytes, stride: int, height: int, bpp: int) -> np.ndarray:
    out = np.zeros((height, stride), dtype=np.uint8)
    prev = np.zeros(stride, dtype=np.int32)
    i = 0
    for y in range(height):
        f = raw[i]
        i += 1
        row = np.frombuffer(raw[i:i + stride], dtype=np.uint8).astype(np.int32)
        i += stride
        if f == 1:    # Sub
            for x in range(bpp, stride):
                row[x] = (row[x] + row[x - bpp]) & 0xFF
        elif f == 2:  # Up
            row = (row + prev) & 0xFF
        elif f == 3:  # Average
            for x in range(stride):
                left = row[x - bpp] if x >= bpp else 0
                row[x] = (row[x] + ((left + prev[x]) >> 1)) & 0xFF
        elif f == 4:  # Paeth
            for x in range(stride):
                a = row[x - bpp] if x >= bpp else 0
                b = prev[x]
                c = prev[x - bpp] if x >= bpp else 0
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                pr = a if (pa <= pb and pa <= pc) else b if pb <= pc else c
                row[x] = (row[x] + pr) & 0xFF
        out[y] = row
        prev = row
    return out


def _unpack_indices(row_bytes: np.ndarray, width: int, depth: int) -> np.ndarray:
    """Expand 1/2/4-bit packed samples to per-pixel indices."""
    if depth == 8:
        return row_bytes[:, :width]
    mask = (1 << depth) - 1
    per_byte = 8 // depth
    n = (width + per_byte - 1) // per_byte
    b = row_bytes[:, :n]
    shifts = np.arange(per_byte - 1, -1, -1) * depth
    unpacked = ((b[:, :, None] >> shifts) & mask).reshape(b.shape[0], -1)
    return unpacked[:, :width]


def _decode_png_rgba(data: bytes) -> np.ndarray:
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError("not a PNG")
    pos = 8
    idat = bytearray()
    width = height = 0
    bit_depth = color_type = 0
    palette: list[tuple[int, int, int]] = []
    trns: bytes = b""
    while pos < len(data):
        (length,) = struct.unpack(">I", data[pos:pos + 4])
        ctype = data[pos + 4:pos + 8]
        chunk = data[pos + 8:pos + 8 + length]
        pos += 12 + length
        if ctype == b"IHDR":
            width, height, bit_depth, color_type = struct.unpack(">IIBB", chunk[:10])
        elif ctype == b"PLTE":
            palette = [tuple(chunk[i:i + 3]) for i in range(0, len(chunk), 3)]  # type: ignore[misc]
        elif ctype == b"tRNS":
            trns = chunk
        elif ctype == b"IDAT":
            idat.extend(chunk)
        elif ctype == b"IEND":
            break
    raw = zlib.decompress(bytes(idat))
    bpp_map = {0: 1, 2: 3, 3: 1, 6: 4}
    if color_type not in bpp_map:
        raise ValueError(f"unsupported colour type {color_type}")
    channels = bpp_map[color_type]
    if color_type in (2, 6) and bit_depth != 8:
        raise ValueError(f"unsupported bit depth {bit_depth}")
    if color_type in (0, 3) and bit_depth not in (1, 2, 4, 8):
        raise ValueError(f"unsupported bit depth {bit_depth}")
    if bit_depth < 8:
        stride = (width * bit_depth + 7) // 8
        bpp = 1
    else:
        stride = width * channels
        bpp = channels
    rows = _unfilter(raw, stride, height, bpp)
    if color_type == 3:
        idx = _unpack_indices(rows, width, bit_depth).astype(np.int64)
        pal = np.array(palette, dtype=np.uint8)
        rgb = pal[idx]
        a = np.full((height, width), 255, dtype=np.uint8)
        if trns:
            t = np.frombuffer(trns, dtype=np.uint8)
            lut = np.pad(t, (0, max(0, len(palette) - len(t))), constant_values=255)
            a = lut[idx]
        return np.dstack([rgb, a])
    if color_type == 0:
        idx = _unpack_indices(rows, width, bit_depth).astype(np.int64)
        g = np.clip(idx * 255 // ((1 << bit_depth) - 1), 0, 255).astype(np.uint8)
        a = np.full((height, width), 255, dtype=np.uint8)
        return np.dstack([g, g, g, a])
    pix = rows.reshape(height, width, channels)
    if color_type == 2:
        a = np.full((height, width, 1), 255, dtype=np.uint8)
        return np.dstack([pix, a])
    return pix


def _avg_color(rgba: np.ndarray) -> tuple[float, float, float] | None:
    """Mean RGB over opaque pixels, or None if fully transparent."""
    if rgba.ndim != 3 or rgba.shape[2] != 4:
        return None
    mask = rgba[:, :, 3] > 127
    if not mask.any():
        return None
    sel = rgba[mask].astype(np.float64)[:, :3] / 255.0
    m = sel.mean(axis=0)
    return (float(m[0]), float(m[1]), float(m[2]))


def _is_grayish(rgb: tuple[float, float, float], tol: float = 0.06) -> bool:
    hi, lo = max(rgb), min(rgb)
    return (hi - lo) <= tol


def _load_version_dataset(assets_version: str, timeout: float) -> tuple[
        dict[str, str], dict[str, str | None], dict[str, tuple[float, float, float]]]:
    """Return (block->texture path, texture->base64 png, colormap tints)."""
    base = _RAW + f"data/{assets_version}/"
    bt = json.loads(_http_get(base + "blocks_textures.json", timeout))
    tc = json.loads(_http_get(base + "texture_content.json", timeout))
    textures: dict[str, str | None] = {
        e["name"]: e.get("texture") for e in tc if isinstance(e, dict)}
    block_tex: dict[str, str] = {}
    for e in bt:
        if not isinstance(e, dict):
            continue
        name = e.get("name")
        tex = e.get("texture")
        if name and tex and isinstance(tex, str):
            block_tex[str(name)] = tex.split(":")[-1].split("/")[-1]
    tints: dict[str, tuple[float, float, float]] = {}
    for cmap_name, key in (("colormap/grass.png", "grass"), ("colormap/foliage.png", "foliage")):
        try:
            raw = _http_get(base + cmap_name, timeout)
            rgba = _decode_png_rgba(raw)
            h, w = rgba.shape[0], rgba.shape[1]
            # plains-ish: a bit left of centre horizontally, upper half
            px = rgba[h // 4, w // 3].astype(np.float64) / 255.0
            if px[3] > 0.5:
                tints[key] = (float(px[0]), float(px[1]), float(px[2]))
        except Exception:
            continue
    return block_tex, textures, tints


# Blocks whose particle/top texture in blocks_textures is misleading; the
# curated color wins over the computed one.
_MANUAL_OVERRIDES: dict[str, tuple[float, float, float]] = {
    "grass_block": (0.53, 0.72, 0.33),   # plains-green top, not the dirt side
    "water": (0.24, 0.42, 0.82),         # vanilla water tint (#3F76E4-ish)
}


def _resolve_texture_key(key: str, textures: dict[str, str | None]) -> str | None:
    """Map a blocks_textures ref to a texture_content key with fallbacks.

    e.g. ``oak_log_top`` -> ``oak_log``, ``water_still`` -> ``water``,
    ``suspicious_sand_0`` -> ``suspicious_sand``.
    """
    if textures.get(key):
        return key
    base = re.sub(r"_\\d+$", "", key)
    for cand in (re.sub(r"_(top|front|side|still|flow)$", "", key),
                 base,
                 re.sub(r"_(top|front|side|still|flow)$", "", base)):
        if cand and textures.get(cand):
            return cand
    return None


def compute_block_colors(assets_version: str, *, timeout: float = 60.0) -> dict[str, list[float]]:
    """Compute average texture colors for every block in a snapshot."""
    block_tex, textures, tints = _load_version_dataset(assets_version, timeout)
    cache: dict[str, tuple[float, float, float] | None] = {}
    out: dict[str, list[float]] = {}
    for block, tex_path in sorted(block_tex.items()):
        short0 = block.split(":")[-1]
        if short0 in _MANUAL_OVERRIDES:
            out[f"minecraft:{short0}"] = [round(c, 4) for c in _MANUAL_OVERRIDES[short0]]
            continue
        # Prefer a texture named exactly like the block (main/top face)
        # over the particle texture referenced by blocks_textures.
        tex_key = short0 if textures.get(short0) else _resolve_texture_key(tex_path, textures)
        uri = textures.get(tex_key) if tex_key else None
        if not uri or tex_key is None:
            continue
        tex_path = tex_key
        if tex_path not in cache:
            png = base64.b64decode(str(uri).split(",", 1)[-1])
            try:
                cache[tex_path] = _avg_color(_decode_png_rgba(png))
            except Exception:
                cache[tex_path] = None
        rgb = cache[tex_path]
        if rgb is None:
            continue
        name = block.split(":")[-1]
        short = name
        tinted = False
        if short in _TINTED_GRASS and "grass" in tints and _is_grayish(rgb):
            t = tints["grass"]
            rgb = (rgb[0] * t[0] * 2, rgb[1] * t[1] * 2, rgb[2] * t[2] * 2)
            tinted = True
        elif ("foliage" in tints and short in _FOLIAGE_FIXED and _is_grayish(rgb)):
            t = tints["foliage"]
            lumin = (rgb[0] + rgb[1] + rgb[2]) / 3.0
            rgb = (lumin * t[0] * 2, lumin * t[1] * 2, lumin * t[2] * 2)
            tinted = True
        if tinted:
            rgb = tuple(min(1.0, max(0.0, c)) for c in rgb)  # type: ignore[assignment]
        out[f"minecraft:{short}"] = [round(float(c), 4) for c in rgb]
    return out


def download_block_colors(mc_version: str, *, cache_root: str | Path | None = None,
                          force: bool = False, timeout: float = 60.0) -> Path:
    """Fetch + cache a version-specific color table; returns the JSON path."""
    root = Path(cache_root) if cache_root else _default_cache_root()
    dest_dir = root / "data" / "pc" / mc_version
    dest = dest_dir / "block_colors.json"
    if dest.exists() and not force:
        return dest
    assets_version = best_assets_version(mc_version, timeout=timeout)
    colors = compute_block_colors(assets_version, timeout=timeout)
    dest_dir.mkdir(parents=True, exist_ok=True)
    payload: dict[str, Any] = {
        "format": 1,
        "mc_version": mc_version,
        "assets_version": assets_version,
        "source": f"https://github.com/{_OWNER}/{_ASSETS_REPO} data/{assets_version}",
        "colors": colors,
    }
    dest.write_text(json.dumps(payload, indent=1), encoding="utf-8")
    return dest


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description="Fetch texture-derived block colors from minecraft-assets.")
    p.add_argument("version", nargs="?", help="Minecraft PC version, e.g. 1.20.1")
    p.add_argument("--list", action="store_true", help="list minecraft-assets versions")
    p.add_argument("--assets", help="force this minecraft-assets snapshot version")
    p.add_argument("--force", action="store_true", help="overwrite cache")
    p.add_argument("--timeout", type=float, default=60.0)
    args = p.parse_args(argv)
    if args.list:
        for v in list_assets_versions(timeout=args.timeout):
            print(v)
        return 0
    if not args.version:
        p.error("version is required unless --list is given")
    av = args.assets or best_assets_version(args.version, timeout=args.timeout)
    colors = compute_block_colors(av, timeout=args.timeout)
    root = _default_cache_root()
    dest = root / "data" / "pc" / args.version / "block_colors.json"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(json.dumps({
        "format": 1, "mc_version": args.version, "assets_version": av,
        "source": f"https://github.com/{_OWNER}/{_ASSETS_REPO} data/{av}",
        "colors": colors,
    }, indent=1), encoding="utf-8")
    print(f"computed {len(colors)} block colors from assets {av} -> {dest}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
