"""Render VoxelGrid to PNG previews (top/front/right/iso) via matplotlib voxels."""
from __future__ import annotations

import hashlib
import warnings
from functools import lru_cache
from pathlib import Path
from typing import Any

import numpy as np

from ..blocks.block import Block
from ..core.chunked import ChunkedGrid
from ..core.palette import Palette
from ..core.voxel import VoxelGrid
from ..resources import load_json_resource

_DENSE_VOXEL_RENDER_LIMIT = 96 ** 3
# Beyond ~45k filled voxels matplotlib's per-face 3D shading becomes
# unusably slow (measured: ~180k filled voxels took > 10 minutes per view),
# so larger-but-dense builds fall back to the fast projected previews.
_DENSE_FILLED_RENDER_LIMIT = 45_000
_PROJECTED_MAX_DIM = 256

# ---------------------------------------------------------------------------
# Block color resolution chain (first hit wins):
#   1. ``SCHEMATICA_BLOCK_COLORS`` env override file (JSON), last-write-wins
#   2. cached per-version ``data/pc/<v>/block_colors.json`` under the
#      minecraft-data root (generated by ``python -m schematica.blocks.colors``)
#      merged oldest -> newest so the newest cached version wins
#   3. bundled ``schematica/data/block_colors.json`` (987 colors averaged from
#      vanilla textures; regenerate via the same tool)
#   4. family heuristic: strip variant suffixes/prefixes until a name hits
#      (``polished_granite_stairs`` -> ``minecraft:polished_granite``)
#   5. stable name hash (last resort, deterministic)
# ---------------------------------------------------------------------------


_VARIANT_SUFFIXES = (
    "_slab", "_stairs", "_wall", "_fence_gate", "_fence", "_pressure_plate",
    "_button", "_trapdoor", "_wall_sign", "_sign", "_door", "_pane",
    "_carpet", "_bed",
)
_VARIANT_PREFIXES = (
    "waxed_", "oxidized_", "weathered_", "exposed_", "cracked_", "mossy_",
    "chiseled_", "cut_", "polished_", "smooth_", "infested_",
)



def _extract_colors(payload: object) -> dict[str, tuple[float, float, float]]:
    """Accept either {"colors": {name: [r,g,b]}} or a flat {name: [r,g,b]}."""
    if not isinstance(payload, dict):
        return {}
    inner: Any = payload.get("colors")
    d: dict[str, Any] = inner if isinstance(inner, dict) else payload
    out: dict[str, tuple[float, float, float]] = {}
    for k, v in d.items():
        if isinstance(v, (list, tuple)) and len(v) == 3:
            vals = [float(c) for c in v]
            if any(c > 1.0 for c in vals):  # tolerate 0-255 tables
                vals = [c / 255.0 for c in vals]
            name = k if ":" in k else f"minecraft:{k}"
            out[name] = (vals[0], vals[1], vals[2])
    return out


@lru_cache(maxsize=1)
def _load_block_colors() -> dict[str, tuple[float, float, float]]:
    table: dict[str, tuple[float, float, float]] = {}
    try:  # bundled baseline
        table.update(_extract_colors(load_json_resource("block_colors.json")))
    except Exception:
        pass
    try:  # per-version caches under the minecraft-data root
        from ..blocks.registry import BlockRegistry
        for ver in BlockRegistry.list_versions():
            from ..blocks.registry import _default_data_root
            p = _default_data_root() / "data" / "pc" / ver / "block_colors.json"
            if p.exists():
                import json as _json
                table.update(_extract_colors(_json.loads(p.read_text(encoding="utf-8"))))
    except Exception:
        pass
    try:  # explicit env override wins last
        table.update(_extract_colors(load_json_resource("block_colors.json",
                                                        env_var="SCHEMATICA_BLOCK_COLORS")))
    except Exception:
        pass
    return table


def _tbl_get(table: dict[str, tuple[float, float, float]], short: str
             ) -> tuple[float, float, float] | None:
    """Lookup with simple singular/plural tolerance (brick <-> bricks)."""
    for cand in (short, short + "s" if not short.endswith("s") else short[:-1]):
        hit = table.get(f"minecraft:{cand}")
        if hit is not None:
            return hit
    return None


def _derived_color(name: str, table: dict[str, tuple[float, float, float]]
                   ) -> tuple[float, float, float] | None:
    """Walk variant families toward a base material color."""
    short = name.split(":")[-1]
    candidates = [short]
    for _ in range(4):  # iterative suffix/prefix stripping
        cur = candidates[-1]
        nxt = None
        for suf in _VARIANT_SUFFIXES:
            if cur.endswith(suf) and len(cur) > len(suf):
                nxt = cur[: -len(suf)]
                break
        if nxt is None:
            for pre in _VARIANT_PREFIXES:
                if cur.startswith(pre) and len(cur) > len(pre):
                    nxt = cur[len(pre):]
                    break
        if nxt is None:
            break
        candidates.append(nxt)
        hit = _tbl_get(table, nxt)
        if hit is not None:
            return hit
    for cand in candidates:
        hit = _tbl_get(table, cand)
        if hit is not None:
            return hit
    return None


def _color_for(block: Block) -> tuple[float, float, float]:
    if block.name == "minecraft:air":
        return (0.0, 0.0, 0.0)
    table = _load_block_colors()
    c = table.get(block.name)
    if c:
        return c
    d = _derived_color(block.name, table)
    if d is not None:
        return d
    # Hash name -> stable color (last resort, e.g. modded blocks)
    digest = hashlib.blake2s(block.name.encode("utf-8"), digest_size=3).digest()
    r = digest[0] / 255.0
    g = digest[1] / 255.0
    b = digest[2] / 255.0
    # lighten a bit
    return (min(r + 0.2, 1.0), min(g + 0.2, 1.0), min(b + 0.2, 1.0))


# Backwards-compatible alias: the active merged color table as a plain dict.
# (Formerly a small hardcoded mapping; now texture-derived + overridable.)
_BLOCK_COLORS: dict[str, tuple[float, float, float]] = _load_block_colors()


def _build_color_array(grid: VoxelGrid) -> np.ndarray:
    sx, sy, sz = grid.shape
    rgba = np.zeros((sx, sy, sz, 4), dtype=float)
    palette = grid.palette.blocks()
    for i, b in enumerate(palette):
        r, g, bcol = _color_for(b)
        sel = grid.data == i
        rgba[sel] = (r, g, bcol, 1.0 if b.name != "minecraft:air" else 0.0)
    return rgba


def _palette_color_array(palette: Palette) -> np.ndarray:
    colors = np.zeros((len(palette), 4), dtype=float)
    for i, b in enumerate(palette.blocks()):
        r, g, bcol = _color_for(b)
        colors[i] = (r, g, bcol, 0.0 if b.name == "minecraft:air" else 1.0)
    return colors


def _render_view(grid: VoxelGrid, elev: int, azim: int, out: Path, *, title: str,
                  size: tuple[int, int] = (6, 6)) -> Path:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from mpl_toolkits.mplot3d import Axes3D  # noqa: F401

    sx, sy, sz = grid.shape
    fig = plt.figure(figsize=size, dpi=100)
    ax = fig.add_subplot(111, projection="3d")
    ax.set_title(title)
    ax.set_box_aspect((sx, sy, sz))
    rgba = _build_color_array(grid)
    filled = grid.data != 0
    # matplotlib voxels wants full-shape arrays
    rgba_vox = rgba.copy()
    rgba_vox[..., 3] = np.where(filled, 1.0, 0.0)
    ax.voxels(filled, facecolors=rgba_vox, edgecolors=(0.05, 0.05, 0.05, 0.25))
    ax.view_init(elev=elev, azim=azim)
    ax.set_xlabel("X")
    ax.set_ylabel("Y")
    ax.set_zlabel("Z")
    plt.tight_layout()
    fig.savefig(out)
    plt.close(fig)
    return out


def preview(grid: VoxelGrid | ChunkedGrid, out_dir: str | Path,
            views: tuple[str, ...] = ("top", "front", "right", "iso"), *,
            max_voxels: int = _DENSE_VOXEL_RENDER_LIMIT,
            max_filled: int = _DENSE_FILLED_RENDER_LIMIT,
            max_dim: int = _PROJECTED_MAX_DIM) -> list[Path]:
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    if isinstance(grid, ChunkedGrid):
        return preview_chunked(grid, out_dir, views, max_dim=max_dim)
    filled = int(np.count_nonzero(grid.data))
    if grid.volume > max_voxels or filled > max_filled:
        warnings.warn(
            f"grid (volume {grid.volume}, filled {filled}) exceeds 3D voxel preview "
            f"limits (volume {max_voxels}, filled {max_filled}); "
            f"using downsampled projected previews (fast)",
            RuntimeWarning,
            stacklevel=2,
        )
        return _preview_projected_dense(grid, out_dir, views, max_dim=max_dim)
    views_map: dict[str, tuple[int, int]] = {
        "top": (90, -90),
        "front": (0, -90),
        "right": (0, 0),
        "iso": (30, 45),
    }
    paths: list[Path] = []
    for v in views:
        elev, azim = views_map.get(v, (30, 45))
        out = out_dir / f"preview_{v}.png"
        _render_view(grid, elev, azim, out, title=v)
        paths.append(out)
    return paths


def _preview_projected_dense(grid: VoxelGrid, out_dir: Path,
                             views: tuple[str, ...], *, max_dim: int) -> list[Path]:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    ds = max(1, (max(grid.shape) + max_dim - 1) // max_dim)
    colors = _palette_color_array(grid.palette)
    paths: list[Path] = []
    for v in views:
        plane = _project_dense_indices(grid, v, ds)
        img = colors[plane]
        fig = plt.figure(figsize=(6, 6), dpi=100)
        ax = fig.add_subplot(111)
        ax.imshow(np.rot90(img), origin="upper")
        ax.set_title(f"{v} projected (ds={ds})")
        ax.axis("off")
        out = out_dir / _projected_preview_name(v)
        fig.savefig(out, bbox_inches="tight")
        plt.close(fig)
        paths.append(out)
    return paths


def _project_dense_indices(grid: VoxelGrid, view: str, ds: int) -> np.ndarray:
    data = grid.data
    sx, sy, sz = grid.shape
    solid = data != 0
    if view == "front":
        has = solid.any(axis=2)
        rev_depth = np.argmax(solid[:, :, ::-1], axis=2)
        z_idx = sz - 1 - rev_depth
        x_idx = np.arange(sx)[:, None]
        y_idx = np.arange(sy)[None, :]
        plane = data[x_idx, y_idx, z_idx]
    elif view == "right":
        has = solid.any(axis=0)
        rev_depth = np.argmax(solid[::-1, :, :], axis=0)
        x_idx = sx - 1 - rev_depth
        y_idx = np.arange(sy)[:, None]
        z_idx = np.arange(sz)[None, :]
        plane = data[x_idx, y_idx, z_idx].T
        has = has.T
    else:
        # Top and the large-grid iso fallback both use a top-down projection.
        has = solid.any(axis=1)
        rev_depth = np.argmax(solid[:, ::-1, :], axis=1)
        y_idx = sy - 1 - rev_depth
        x_idx = np.arange(sx)[:, None]
        z_idx = np.arange(sz)[None, :]
        plane = data[x_idx, y_idx, z_idx]
    plane = np.where(has, plane, 0)
    return plane[::ds, ::ds]


def _color_array_from_palette(palette: Palette) -> dict[int, tuple[float, float, float, float]]:
    out: dict[int, tuple[float, float, float, float]] = {}
    for i, b in enumerate(palette.blocks()):
        r, g, bcol = _color_for(b)
        out[i] = (r, g, bcol, 0.0 if b.name == "minecraft:air" else 1.0)
    return out


def preview_chunked(grid: ChunkedGrid, out_dir: str | Path,
                      views: tuple[str, ...] = ("top", "front", "right", "iso"),
                      *, max_dim: int = 256) -> list[Path]:
    """Render a ChunkedGrid without materialising a full dense array.

    Builds per-view 2D images by projecting touched chunks. ``max_dim``
    caps the longest axis of the rendered image so memory stays bounded for
    maps spanning hundreds of chunks.
    """
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    sx, sy, sz = grid.shape
    # Downsample factor so no rendered side exceeds max_dim.
    ds = max(1, (max(sx, sy, sz) + max_dim - 1) // max_dim)
    colors = _color_array_from_palette(grid.palette)
    paths: list[Path] = []
    view_specs = {
        "top": ("xz", "y", "top"),
        "front": ("xy", "z", "front"),
        "right": ("zy", "x", "right"),
        "iso": ("xz", "y", "iso"),
    }
    for v in views:
        plane, depth_axis, title = view_specs.get(v, ("xz", "y", v))
        img = _project_chunked(grid, plane, depth_axis, colors, ds)
        fig = plt.figure(figsize=(6, 6), dpi=100)
        ax = fig.add_subplot(111)
        ax.imshow(np.rot90(img), origin="upper")
        ax.set_title(f"{title} (ds={ds})")
        ax.axis("off")
        out = out_dir / _projected_preview_name(v)
        fig.savefig(out, bbox_inches="tight")
        plt.close(fig)
        paths.append(out)
    return paths


def preview_region(grid: VoxelGrid | ChunkedGrid, corner: tuple[int, int, int],
                    size: tuple[int, int, int], out_dir: str | Path,
                    views: tuple[str, ...] = ("top", "front", "right", "iso"), *,
                    max_voxels: int = _DENSE_VOXEL_RENDER_LIMIT,
                    max_filled: int = _DENSE_FILLED_RENDER_LIMIT,
                    max_dim: int = _PROJECTED_MAX_DIM) -> list[Path]:
    """Render a cropped sub-region of the grid.

    This extracts ``grid[corner .. corner+size]`` as a small dense grid and
    runs the standard ``preview()`` pipeline on it. Useful for reviewing a
    single team base, spawn platform, or focal structure on large maps without
    waiting for a full-map render.
    """
    x0, y0, z0 = corner
    sx, sy, sz = size
    if sx <= 0 or sy <= 0 or sz <= 0:
        raise ValueError(f"region size must be positive, got {size}")
    gx, gy, gz = grid.shape
    if x0 < 0 or y0 < 0 or z0 < 0 or x0 + sx > gx or y0 + sy > gy or z0 + sz > gz:
        raise ValueError(f"region {corner}+{size} is outside grid {grid.shape}")
    sub = grid.subregion(corner, size)
    return preview(sub, out_dir, views, max_voxels=max_voxels,
                   max_filled=max_filled, max_dim=max_dim)


def _projected_preview_name(view: str) -> str:
    if view == "iso":
        return "preview_iso_projected.png"
    return f"preview_{view}.png"


def _project_chunked(grid: ChunkedGrid, plane: str, depth_axis: str,
                     colors: dict[int, tuple[float, float, float, float]],
                     ds: int) -> np.ndarray:
    """Project touched chunks onto a 2D plane, downsampling by ``ds``.

    Uses max-projection along ``depth_axis`` (frontmost solid voxel wins) so the
    result is a bounded 2D silhouette even for very large sparse maps.
    """
    sx, sy, sz = grid.shape
    if plane == "xz":
        w, h = sx, sz
    elif plane == "xy":
        w, h = sx, sy
    elif plane == "zy":
        w, h = sz, sy
    else:
        raise ValueError(f"unknown preview plane {plane!r}")
    img = np.zeros(((w + ds - 1) // ds, (h + ds - 1) // ds, 4), dtype=float)
    depth = np.full(img.shape[:2], -1, dtype=int)
    for (cx, cy, cz), arr in grid._chunks.items():
        cs = grid.chunk_size
        ox = cx * cs
        oy = cy * cs
        oz = cz * cs
        xs, ys, zs = np.nonzero(arr)
        for lx, ly, lz in zip(xs, ys, zs, strict=False):
            x = ox + int(lx)
            y = oy + int(ly)
            z = oz + int(lz)
            if plane == "xz":
                px, py = x // ds, z // ds
            elif plane == "xy":
                px, py = x // ds, y // ds
            else:
                px, py = z // ds, y // ds
            d = {"x": x, "y": y, "z": z}[depth_axis]
            if d >= depth[px, py]:
                depth[px, py] = d
                img[px, py] = colors.get(int(arr[lx, ly, lz]), (0.5, 0.5, 0.5, 1.0))
    return img
